### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by SRL94** [RDFLib/rdflib-hdt#13]
Hi,

Is it compatible with Windows? I have tried to install it through pip on Windowns 10 but I got some errors.

Best regards
Sirui

**Comment by Callidon** [comment]
Hi,
since this is a python binding of the hdt c++ library, it requires a c++ compilation during installation. Unfortunately, compiling C++ on windows might be quite tricky depending on your actual setup. 
What errors are you encountering exactly? Another issue #2  was opened some time ago with similar concerns, maybe it can help you.

**Comment by SRL94** [comment]
I installed WSL2 on my Win10. This library can be installed and work without any issue on WSL2.
