### ISSUE TITLE
HDTStore.triples incorrectly has 'context' as positional argument

### ISSUE THREAD

**Issue by wxwilcke** [RDFLib/rdflib-hdt#8]
**Describe the bug**
When looping over the triples in a HDTStore object using the 'triples(pattern, context)' function, the context argument cannot be left out or given as 'None'. The description in README.md indicates that the context should be optional. Moreover, requiring only the pattern is the expected behaviour with the regular RDFlib graph stores.

**To Reproduce**
```
from rdflib import Graph
from rdflib_hdt import HDTStore
RDFLib Version: 5.0.0

g = HDTStore("data.hdt")
for s,p,o in g.triples((None, None, None)):
    continue

TypeError: triples() missing 1 required positional argument: 'context'
```

**Expected behavior**
The above code without error, i.e, make 'context' optional. Note that the following code, which is executed under the hood, works fine:

```
for s,p,o in g.hdt_document.search((None, None, None))[0]:
    continue
```

**Comment by CaptSolo** [comment]
Does this function actually use the `context` argument? Looks like it does not:

https://github.com/RDFLib/rdflib-hdt/blob/c5dc26373be37a0a96f31eede78a2e8e0b2fa251/rdflib_hdt/hdt_store.py#L63-L75

**Comment by Callidon** [comment]
`HDTStore` is a class designed to be used as backend by rdflib's `Graph` class, so you are not meant to use it directly. As shown in the project's README and rdflib doc, this is the correct usage of the library
```python
from rdflib import Graph
from rdflib_hdt import HDTStore
from rdflib.namespace import FOAF

store = HDTStore("test.hdt")
graph = Graph(store=store)
for s, p, o in graph.triples((None, FOAF("name"), None)):
  print(triple)
```

About the `context` argument: it is injected by rdflib automatically during query processing (triple matching or full SPARQL query evaluation). So, even if we do not use it in the `HDTSore`, we need to put it in the function parameters, otherwise rdflib will reject it as a valid store. Again, this method is not supposed to be used by end-user, and is reserved to rdflib internals.

**Comment by wxwilcke** [comment]
Thank you for your reply. Coming from pyHDT, I completed missed the expected workflow of setting the HDTStore object as data store instead of directly working with it.
